Gmsys/urls.py
# -*- coding:utf-8 -*-
"""Gmsys URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include, re_path
from index.views import IndexView, InformationView, AtsintroduceView, AllinforView
from users.views import LoginView, LogoutView
from todolists.views import TodolistView, UsualtodoView
from plans.views import PlansView
from comprehensive.views import SchedulingView
from question.views import QuestionsView, QuestionBankView
import xadmin
from django.views.static import serve
from Gmsys.settings import MEDIA_ROOT,STATICFILES_DIRS,STATIC_URL

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('', IndexView.as_view(), name="index"),
    path('infor/id=<int:id>', InformationView.as_view(), name="infor"),
    path('intro/', AtsintroduceView.as_view(), name="intro"),
    path('allinfor/', AllinforView.as_view(), name="allinfor"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('todolist/', TodolistView.as_view(), name="todolist"),
    path('usualtodo/', UsualtodoView.as_view(), name="usualtodo"),
    path('plan/', PlansView.as_view(), name="plan"),
    path('sche/', SchedulingView.as_view(), name="sche"),
    path('que/', include('question.urls', namespace="que")),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    re_path(r'^ueditor/', include('DjangoUeditor.urls')),
    re_path(r'^static/(?P<path>.*)$',serve,{'document_root': STATICFILES_DIRS}),
]

apps/question/urls.py
# -*-coding:utf-8 -*-
from django.urls import path,include
from .views import QuestionsView,QuestionBankView
app_name = 'que'
urlpatterns = [
    path('dayly/', QuestionsView.as_view(), name="question"),
    path('bank/', QuestionBankView.as_view(), name="questionbank"),
]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/todolists/forms.py
# -*-coding:utf-8 -*-
from django import forms



class TodoForm(forms.Form):
    add_todo = forms.CharField(widget=forms.Textarea,required=True)
    work_type = forms.CharField(required=True)
    priority = forms.CharField(required=True)
    member_name = forms.CharField(required=True)

class TodoModalForm(forms.Form):
    todotext = forms.CharField(widget=forms.Textarea,required=True)
    work_type_modal = forms.CharField(required=True)
    priority_modal = forms.CharField(required=True)
    member_name_modal = forms.CharField(required=True)

class UsualTodoModalForm(forms.Form):
    usual_todotext = forms.CharField(widget=forms.Textarea,required=True)
    usual_work_type_modal = forms.CharField(required=True)
    usual_priority_modal = forms.CharField(required=True)
    usual_member_name_modal = forms.CharField(required=True)

apps/plans/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render
from django.views.generic.base import View
from .models import PlanTitle,PlanArticle,Maintain,PlanYear
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
import datetime
from users.utils import LoginRequiredMixin
# Create your views here.

class PlansView(LoginRequiredMixin,View):
    def get(self,request):
        pltitles = PlanTitle.objects.filter(id=1)
        plarticles = PlanArticle.objects.all().filter(article_year__plan_year=datetime.datetime.now().year).order_by("-add_time")
        maintains = Maintain.objects.filter(id=1).values()
        planyears = PlanYear.objects.all()

        #对年度进行筛选
        article_year = request.GET.get('year',"")
        if article_year:
            plarticles = PlanArticle.objects.all().filter(article_year_id = article_year)

        # Plans进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        objects = ['john', 'edward', 'josh', 'frank']

        # Provide Paginator with the request object for complete querystring generation

        p = Paginator(plarticles, 12, request=request)

        allplart = p.page(page)

        return render(request,'plan.html',{
        "pltitles":pltitles,
        "plarticles":allplart,
        "maintains":maintains,
        "artiyear":article_year,
        "planyears":planyears,


        })

apps/question/views.py
from django.shortcuts import render
from django.views.generic.base import View
from .models import CourseType, QuestionBank, MemberQuestionRecord
from django.http import HttpResponseRedirect
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from users.utils import LoginRequiredMixin


# Create your views here.

class QuestionsView(LoginRequiredMixin, View):
    def get(self, request):
        all_question = QuestionBank.objects.all().order_by('?')[:1]

        return render(request, 'question.html', {
            "all_question": all_question
        })

    def post(self, request):
        record = MemberQuestionRecord()
        record.user_name_id = request.user.id
        record.record_answer = request.POST.get('answer_question')
        record.course_type_id = request.POST.get('course_type_id')
        record.record_question_title_id = request.POST.get('record_question_title_id')
        record.save()
        return HttpResponseRedirect('/que/bank/?qn=' + record.record_question_title_id)



class QuestionBankView(LoginRequiredMixin, View):
    def get(self, request):
        all_question = QuestionBank.objects.all()

        # 题号搜索
        question_id = request.GET.get('qn', "")
        if question_id:
            all_question = all_question.filter(id=question_id)

        # question进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        objects = ['john', 'edward', 'josh', 'frank']

        # Provide Paginator with the request object for complete querystring generation

        p = Paginator(all_question, 50, request=request)

        questions = p.page(page)

        return render(request, 'questionbank.html', {
            "all_question": questions,
            "question_id": question_id
        })

apps/todolists/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render
from django.views.generic.base import View
from apps.todolists.models import Todo, UsualTodo
from users.models import UserProfile
from django.http import HttpResponseRedirect
from .forms import TodoForm, TodoModalForm,UsualTodoModalForm
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
import datetime
from django.db.models import Q
from users.utils import LoginRequiredMixin


# Create your views here.

class TodolistView(LoginRequiredMixin,View):
    def get(self, request):
            all_todo = Todo.objects.all().order_by("is_done","plan_done_time","priority")
            all_usernames = UserProfile.objects.all()

            # 筛选是否完成
            is_done = request.GET.get('isd',"")
            if is_done:
                all_todo = all_todo.filter(is_done=is_done).order_by("plan_done_time","priority")

            # 优先级筛选
            priority = request.GET.get('pr', "")
            if priority:
                all_todo = all_todo.filter(priority=priority).order_by("is_done","plan_done_time","priority")
            # 取出工作类型
            work_type = request.GET.get('wt', "")
            if work_type:
                all_todo = all_todo.filter(work_type=work_type).order_by("is_done","plan_done_time","priority")

            # 日期筛选:start_date
            start_date = request.GET.get('st', "")
            end_date = request.GET.get('et', "")
            if start_date:
                all_todo = all_todo.filter(plan_done_time__range=(start_date, end_date)).order_by("is_done","plan_done_time","priority")

            # 名字筛选
            member_name = request.GET.get('gn', "")
            if member_name:
                all_todo = all_todo.filter(member_name__icontains=member_name).order_by("is_done","plan_done_time","priority")

            # 删除事项
            del_id = request.GET.get("delid")
            if del_id:
                Todo.objects.filter(id=del_id).delete()

            # 完成事项
            done_id = request.GET.get("doneid")
            if done_id:
                Todo.objects.filter(id=done_id).update(is_done=True, done_time=datetime.datetime.now())

            # 恢复事项
            redo_id = request.GET.get("redoid")
            if redo_id:
                Todo.objects.filter(id=redo_id).update(is_done=False, add_time=datetime.datetime.now())

            # TODOLIST进行分页
            try:
                page = request.GET.get('page', 1)
            except PageNotAnInteger:
                page = 1

            objects = ['john', 'edward', 'josh', 'frank']

            # Provide Paginator with the request object for complete querystring generation

            p = Paginator(all_todo, 50, request=request)

            todos = p.page(page)

            return render(request, "todolist.html", {
                "all_todo": todos,
                "all_usernames": all_usernames,
                "priority": priority,
                "work_type": work_type,
                "is_done": is_done,
                "start_date": start_date,
                "end_date": end_date,
                "member_name": member_name,

            })


    def post(self, request):
        all_todo = Todo.objects.all()
        all_usernames = UserProfile.objects.all()
        add_todo_form = TodoForm(request.POST)
        add_todomodal_form = TodoModalForm(request.POST)

        if add_todo_form.is_valid() or add_todomodal_form.is_valid():
            # add_todotext = request.POST.get("todotext","")
            add_todo = request.POST.get("add_todo")

            if add_todo != None:
                todo = Todo()
                todo.user_name_id = request.user.id
                todo.contents = request.POST.get("add_todo")
                todo.priority = request.POST.get("priority")
                todo.work_type = request.POST.get("work_type")
                todo.is_done = False
                todo.member_name = ','.join(request.POST.getlist("member_name"))
                todo.plan_done_time = request.POST.get("plandonetime")
                todo.save()
                return HttpResponseRedirect('/todolist/')
            else:
                todo = Todo()
                todo.id = request.POST.get("id")
                todo.user_name_id = request.user.id
                todo.contents = request.POST.get("todotext", "")
                todo.priority = request.POST.get("priority_modal")
                todo.work_type = request.POST.get("work_type_modal")
                todo.is_done = False
                todo.member_name = ','.join(request.POST.getlist("member_name_modal"))
                todo.add_time = datetime.datetime.now()
                todo.plan_done_time = request.POST.get("plandonetime_modal")
                todo.save()
                return HttpResponseRedirect('/todolist/')
        else:
            return render(request, "todolist.html", {
                "msg": "提交信息不能为空",
                "add_todo_form": add_todo_form,
                "all_todo": all_todo,
                "all_usernames": all_usernames,
            })


class UsualtodoView(View):
    def get(self, request):
        if request.user.is_authenticated:
            usual_todo = UsualTodo.objects.all().filter(user_name_id=request.user.id).order_by("plan_done_time","priority")
            all_usernames = UserProfile.objects.all()

            # 筛选是否完成
            is_done = request.GET.get('isd', "")
            if is_done:
                usual_todo = usual_todo.filter(is_done=is_done).order_by("plan_done_time","priority")

            # 优先级筛选
            priority = request.GET.get('pr', "")
            if priority:
                usual_todo = usual_todo.filter(priority=priority).order_by("is_done","plan_done_time","priority")
            # 取出工作类型
            work_type = request.GET.get('wt', "")
            if work_type:
                usual_todo = usual_todo.filter(work_type=work_type).order_by("is_done","plan_done_time","priority")

            # 日期筛选:start_date
            start_date = request.GET.get('st', "")
            end_date = request.GET.get('et', "")
            if start_date:
                usual_todo = usual_todo.filter(done_time__range=(start_date, end_date)).order_by("is_done","plan_done_time","priority")

            # 名字筛选
            member_name = request.GET.get('gn', "")
            if member_name:
                usual_todo = usual_todo.filter(member_name=member_name).order_by("is_done","plan_done_time","priority")

            # 删除事项
            del_id = request.GET.get("delid")
            if del_id:
                UsualTodo.objects.filter(id=del_id).delete()

            # 完成事项
            done_id = request.GET.get("doneid")
            if done_id:
                UsualTodo.objects.filter(id=done_id).update(is_done=True, done_time=datetime.datetime.now())

            # 恢复事项
            redo_id = request.GET.get("redoid")
            if redo_id:
                UsualTodo.objects.filter(id=redo_id).update(is_done=False, add_time=datetime.datetime.now())

            # TODOLIST进行分页
            try:
                page = request.GET.get('page', 1)
            except PageNotAnInteger:
                page = 1

            objects = ['john', 'edward', 'josh', 'frank']

            # Provide Paginator with the request object for complete querystring generation

            p = Paginator(usual_todo, 50, request=request)

            todos = p.page(page)

            return render(request, "usualtodolist.html", {
                "usual_todo": todos,
                "all_usernames": all_usernames,
                "priority": priority,
                "work_type": work_type,
                "is_done": is_done,
                "start_date": start_date,
                "end_date": end_date,
                "member_name": member_name,
            })

    def post(self, request):
        all_todo = UsualTodo.objects.all()
        all_usernames = UserProfile.objects.all()
        add_todo_form = TodoForm(request.POST)
        add_todomodal_form = TodoModalForm(request.POST)
        usual_todomodal_form = UsualTodoModalForm(request.POST)

        if add_todo_form.is_valid() or add_todomodal_form.is_valid() or usual_todomodal_form.is_valid():
            usual_todotext = request.POST.get("usual_todotext","")
            add_todo = request.POST.get("add_todo")

            if add_todo != None:
                todo = UsualTodo()
                todo.user_name_id = request.user.id
                todo.contents = request.POST.get("add_todo")
                todo.priority = request.POST.get("priority")
                todo.work_type = request.POST.get("work_type")
                todo.is_done = False
                todo.member_name = ','.join(request.POST.getlist("member_name"))
                todo.plan_done_time = request.POST.get("plandonetime")
                todo.save()
                return HttpResponseRedirect('/usualtodo/')
            elif usual_todotext !="":
                todo = UsualTodo()
                todo.id = request.POST.get("id")
                todo.user_name_id = request.user.id
                todo.contents = request.POST.get("usual_todotext", "")
                todo.priority = request.POST.get("usual_priority_modal")
                todo.work_type = request.POST.get("usual_work_type_modal")
                todo.is_done = False
                todo.member_name = ','.join(request.POST.getlist("usual_member_name_modal"))
                todo.add_time = datetime.datetime.now()
                todo.plan_done_time = request.POST.get("usual_plandonetime_modal")
                todo.save()
                return HttpResponseRedirect('/usualtodo/')
            else:
                todo = Todo()
                todo.user_name_id = request.user.id
                todo.contents = request.POST.get("todotext", "")
                todo.priority = request.POST.get("priority_modal")
                todo.work_type = request.POST.get("work_type_modal")

templates/allinfor.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    信息中心-ATS工班管理系统
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
    <img src="{% static 'images/informations.jpg' %}" class="img-responsive" alt="Responsive image">
    <br>
    <div class="container">
            <br>
        <!-- Main component for a primary marketing message or call to action -->
        {% block brtree %}
            <ol class="breadcrumb">
                <li><a href="/">首页</a></li>
                <li class="active"><a href="{% url 'allinfor' %}">信息中心</a></li>
            </ol>
        {% endblock brtree %}

        <div class="panel panel-default">
            <div class="panel-body">
                {% for infor in allinfor.object_list %}
                    <p><a href="{% url 'infor' infor.id %}">{{ infor.title }}
                        <span class="pull-right">{{ infor.add_time|date:'Y-m-d' }}</span></a></p>
                {% endfor %}
            </div>

            <nav aria-label="Page navigation" class="text-center">
                <ul class="pagination">
                    <li>
                        {% if allinfor.has_previous %}
                            <li class="disabled"><a href="?{{ allinfor.previous_page_number.querystring }}"
                                                    aria-label="Previous"><span
                                    aria-hidden="true">&laquo;</span></a></li>
                        {% endif %}

                    {% for page in allinfor.pages %}
                        {% if page %}
                            {% ifequal page allinfor.number %}
                                <li class="active"><a href="?{{ page.querystring }}">{{ page }} <span
                                        class="sr-only">{{ page }}</span></a></li>
                            {% else %}
                                <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li><a href="">...</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if allinfor.has_next %}
                        <li>
                            <a href="?{{ allinfor.next_page_number.querystring }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    </li>
                </ul>
            </nav>
        </div>


    </div> <!-- /container -->
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
{% load staticfiles %}
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/LOGO.ico' %}">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap-select/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}">
    <!-- Latest compiled and minified CSS -->
</head>

<body style="padding-top: 50px">
<!-- 引入导航栏 -->
{% include 'header.html' %}

<!-- 预留具体页面的位置 -->
{% block content %}
    {% block brtree %}{% endblock brtree %}
{% endblock content %}
<!-- 引入注脚 -->

</body>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap-select/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
<!-- Latest compiled and minified JavaScript -->


<!-- (Optional) Latest compiled and minified JavaScript translation files -->
<script src="{% static 'bootstrap-select/js/i18n/defaults-zh_CN.min.js' %}"></script>
<script src="{% static 'bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script src="{% static 'bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.fr.js' %}"></script>
{% block scrip %}
{% endblock %}

</html>

templates/footer.html
<!-- Footer -->


<footer class="py-3 bg-dark fixed-bottom">

    <div class="panel panel-default">
        <div class="panel-body">
            友情链接
            {% for link in links %}
                <a href="{{ link.url }}">{{ link.title }}</a>
            {% endfor %}
        </div>
    </div>


</footer>

templates/header.html
{% load staticfiles %}
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">ATS班组管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'todolist' %}">待办事项<span class="badge">{{ request.user.message_nums }}</span></a></li>
                <li><a href="{% url 'plan' %}">检修计划</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">综合管理 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'sche' %}">排班计划</a></li>
                        <li><a href="{% url 'que:question' %}">每日一问</a></li>
                        <li><a href="{% url 'que:questionbank' %}">题库</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'allinfor' %}">信息中心</a></li>
                <li><a href="{% url 'intro' %}">班组简介</a></li>
            </ul>
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user.nick_name }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'usualtodo' %}">添加日常计划</a></li>
                            <li><a href="{% url 'logout' %}">退出</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'login' %}">登陆</a></li>
                </ul>
            {% endif %}
        </div><!--/.nav-collapse -->
    </div>
</nav>

templates/index.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页-ATS工班管理系统
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"
                     style="height: 100%;background-position: center;">

                    <ol class="carousel-indicators">

                        <li data-target="#carousel-example-generic" data-slide-to="{{ banner.0.index }}"
                            class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="{{ banner.1.index }}"
                        ></li>
                        <li data-target="#carousel-example-generic" data-slide-to="{{ banner.2.index }}"
                        ></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="{{ MEDIA_URL }}{{ banner.0.image }}" alt="{{ banner.0.title }}">
                            <div class="carousel-caption">
                                {{ banner.0.title }}
                            </div>
                        </div>
                        <div class="item">
                            <img src="{{ MEDIA_URL }}{{ banner.1.image }}" alt="{{ banner.1.title }}">
                            <div class="carousel-caption">
                                {{ banner.1.title }}
                            </div>
                        </div>
                        <div class="item">
                            <img src="{{ MEDIA_URL }}{{ banner.2.image }}" alt="{{ banner.2.title }}">
                            <div class="carousel-caption">
                                {{ banner.2.title }}
                            </div>
                        </div>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <br>
                <div class="row">
                    <div class="col-lg-3 col-xs-12">
                        <img class="featurette-image img-responsive center-block"
                             alt="信息中心"
                             src="{% static 'images/atslogo.jpg' %}"
                             data-holder-rendered="true">
                    </div>
                    <div class="col-lg-9 col-xs-12">
                        <p style="font-size: 30px">信息中心 <a class="btn btn-primary pull-right"
                                                           href="{% url 'allinfor' %}"
                                                           role="button">更多»</a>
                        </p>
                        {% for information in informations %}
                            {% if information.title|length <= 30 %}
                                <p><a href="{% url 'infor' information.id %}">{{ information.title }}<span
                                        class="pull-right">{{ information.add_time|date:"m-d" }}</span></a><br></p>
                            {% else %}
                                <p>
                                    <a href="{% url 'infor' information.id %}">{{ information.title|slice:":30" }}...<span
                                            class="pull-right">{{ information.add_time|date:"m-d" }}</span></a><br></p>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>

            </div>

            <div class="col-sm-3 col-xs-12 well" style="height: 790px">
                <ul id="myTab" class="nav nav-tabs">
                    <li class="active">
                        <a href="#notic" data-toggle="tab">
                            公告
                        </a>
                    </li>
                    <li><a href="#sld" data-toggle="tab">安全学习文件</a></li>
                </ul>
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="notic">
{#                        <p class="text-center">{{ notice.first.title }}</p>#}
                        <p class="lead">{{ notice.first.contents |safe }}</p>
                    </div>
                    <div class="tab-pane fade" id="sld">
                        <p class="lead">{{ notice.first.sld |safe }}</p>
                    </div>
                </div>
            </div>
        </div>

        {% include 'footer.html' %}


    </div> <!-- /container -->

{% endblock content %}

templates/question.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    每日一问-ATS工班管理系统
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
    <img src="{% static 'images/dailyque.jpg' %}" class="img-responsive" alt="Responsive image">
    <div class="container">
    <br>
        <!-- Main component for a primary marketing message or call to action -->
        <form action="{% url 'que:question' %}" method="post" id="question_form" name="question_form">
            {% for question in all_question %}
                <div class="col-md-offset-2 col-md-8">
                    <div class="form-group">
                    <h2>{{ question.id }}、{{ question.question_title }}</h2>
                    </div>
                     <div class="form-group">
                    <input class="hidden" value="{{ question.id }}" id="record_question_title_id" name="record_question_title_id">
                    <input class="hidden" value="{{ question.course_type_id }}" id="course_type_id" name="course_type_id">
                    <input class="hidden" value="{{ question.answer }}" id="hidden_answer" name="hidden_answer">
                    </div>
                    <div class="form-group">
                    <textarea class="form-control" id="answer_question" name="answer_question" placeholder="填写答案" rows="10"
                    required ></textarea>
                    </div>
                    <div class="form-group">
                    <input class="btn btn-success pull-right" type="submit" value="提交" onclick="myFunction()">
                    </div>
                </div>
            {% endfor %}
            {% csrf_token %}
        </form>
    {{ answer }}
    </div> <!-- /container -->
{% endblock content %}